// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXZghxTzwhqb2nxSbbib6YuPOXLiof_uA',
    appId: '1:890356322716:android:d5ebd0e53c8dfbf1fdb859',
    messagingSenderId: '890356322716',
    projectId: 'cheese-movie',
    databaseURL:
        'https://cheese-movie-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cheese-movie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFnL_yt7cqegY08HJ7F3AFJlEWs3tbRGA',
    appId: '1:890356322716:ios:78d5ad4c0c5601bcfdb859',
    messagingSenderId: '890356322716',
    projectId: 'cheese-movie',
    databaseURL:
        'https://cheese-movie-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cheese-movie.appspot.com',
    iosClientId:
        '890356322716-5esj2dvr5ndr8767pesna1kprtc4k1kk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cheeseMovie',
  );
}
